// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much confidence to place in a filesystem's free-space figure.
 */
export type Accounting = "exact" | "tool_reported" | { "approximate": { reason: string, } };
