// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What can be done to a unit. `SVC-2`.
 *
 * A closed set, and typed. Each maps to one D-Bus method, so nothing here is assembled from text.
 */
export type Action = "start" | "stop" | "restart" | "reload" | "enable" | "disable" | "mask" | "unmask";
