// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reclaimable } from "./Reclaimable";

/**
 * Space nix can **see and account for but will not act on itself**.
 *
 * # Why this exists
 *
 * The failure mode this project exists to avoid is space that is real, large, and invisible. But
 * there is a second failure mode just as bad: automating a destructive operation that has never
 * been exercised. Some findings sit between the two — the bytes are certain, the remedy is known,
 * and the tool that would carry it out is either absent or unverified on this machine.
 *
 * Hiding those bytes would repeat the first mistake; offering a button would commit the second. An
 * advisory is the honest third answer: report the size, name the remedy, and say plainly why nix is
 * not doing it. The user keeps the information and the decision.
 *
 * The concrete case that prompted it: 701 MiB of unreferenced objects in this machine's flatpak
 * ostree repository, with no `ostree` binary installed to prune them.
 */
export type Advisory = { 
/**
 * Where it is, when it is a place.
 */
path: string | null, 
/**
 * What the user sees.
 */
label: string, 
/**
 * On-disk bytes, measured the same way a candidate's are.
 */
bytes: number, 
/**
 * How much of `bytes` would actually come back, qualified as honestly as a candidate's.
 */
reclaimable: Reclaimable, 
/**
 * Why nix will not do this itself. Required, because an advisory without this is just a
 * refusal with no explanation.
 */
why_manual: string, 
/**
 * What the user can run instead. A command they can read before they run it.
 */
remedy: string, 
/**
 * Which category reported it.
 */
category: string, };
