// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cause } from "./Cause";
import type { ErrorCode } from "./ErrorCode";

/**
 * The single error type crossing every boundary in nix.
 */
export type AppError = { 
/**
 * Machine-readable class.
 */
code: ErrorCode, 
/**
 * One sentence, plain language, addressed to the user.
 */
message: string, 
/**
 * What the user can do about it, when there is something.
 */
remedy: string | null, 
/**
 * The underlying failure, for the details view and for bug reports.
 *
 * Boxed because it is the largest field and the least often read: keeping it inline pushed
 * `AppError` past clippy's `result_large_err` threshold, which would have made every
 * `Result<T, AppError>` in the codebase expensive to move on the *success* path. Errors are
 * rare, so an allocation here costs nothing that matters.
 */
cause: Cause | null, 
/**
 * Breadcrumb from outermost operation inwards, appended by each layer that wraps.
 */
context: Array<string>, 
/**
 * The path involved, when the failure is about one.
 */
path: string | null, };
