// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";

/**
 * One autostart entry, as the user needs to see it.
 *
 * Exported to TypeScript as `AutostartEntry`: `journal::Entry` is also `Entry`, and ts-rs writes one
 * file per exported name, so two types called `Entry` silently overwrite each other's bindings. The
 * Rust name stays `Entry` because it is always read as `autostart::Entry`.
 */
export type AutostartEntry = { 
/**
 * The file name, which is the entry's identity and what shadowing is keyed on.
 */
id: string, path: string, origin: Origin, name: string, comment: string | null, exec: string, icon: string | null, 
/**
 * Whether this will run at the next login.
 *
 * **`true` unless something says otherwise** — see the module documentation.
 */
enabled: boolean, 
/**
 * `NoDisplay=true`: the entry asks not to be shown in a UI.
 *
 * Honoured as a *sort order and a label*, not as a filter. 40 of the 42 system entries here set
 * it, and hiding them would leave a "startup applications" screen that shows almost nothing —
 * while the thing a user came to stop is very likely among them.
 */
no_display: boolean, 
/**
 * `OnlyShowIn` / `NotShowIn`, verbatim.
 */
only_show_in: Array<string>, not_show_in: Array<string>, 
/**
 * Whether this entry applies to the session that is actually running.
 */
runs_in_this_session: boolean, 
/**
 * `TryExec`: the entry is skipped if this program is not present.
 */
try_exec: string | null, 
/**
 * Whether `TryExec` names something that cannot be found, which means the entry will not run
 * however enabled it looks.
 */
try_exec_missing: boolean, 
/**
 * For a system entry: whether the user directory already shadows it.
 */
shadowed: boolean, 
/**
 * Whether nix can change this entry's state. A system entry is changed by shadowing it, which is
 * always possible, so this is about the file itself.
 */
writable: boolean, };
