// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChargeState } from "./ChargeState";

/**
 * One battery.
 */
export type Battery = { name: string, state: ChargeState, 
/**
 * How full it is now, 0–100.
 */
percent: number, 
/**
 * Capacity now against capacity when new, 0–100. `None` when the firmware does not say.
 */
health_percent: number | null, 
/**
 * Current draw or charge rate in watts. Zero when idle.
 */
watts: number, 
/**
 * Seconds until full or empty. `None` whenever the rate is zero — which is most of the time on
 * mains, and is not the same as "no time left".
 */
seconds_remaining: number | null, cycles: number | null, technology: string | null, };
