// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanResult } from "./ScanResult";

/**
 * One persisted scan.
 */
export type CachedScan = { version: number, 
/**
 * When the scan finished, in seconds since the Unix epoch.
 */
scanned_at: number, 
/**
 * What was scanned.
 */
root: string, 
/**
 * The depth cap in force, so a shallower cached tree is not served for a deeper request.
 */
max_depth: number | null, 
/**
 * Whether the scan crossed filesystem boundaries.
 */
cross_filesystems: boolean, 
/**
 * The result itself.
 */
result: ScanResult, };
