// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something nix needs from the host in order to offer a feature.
 *
 * One variant per *capability*, not per distro. A machine with both `apt` and `flatpak` reports
 * both, and the features that depend on each are offered independently.
 */
export type Capability = "apt" | "dnf" | "pacman" | "zypper" | "snap" | "flatpak" | "systemctl" | "journalctl" | "pkexec" | "btrfs_tools";
