// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";

/**
 * What the host can do, as sent to the frontend.
 *
 * Named `Capabilities` rather than `Snapshot`: it is a capability set, and `cow::Snapshot` is a
 * filesystem snapshot. Two Rust types with the same name generate the same TypeScript file, and
 * one silently overwrites the other.
 */
export type Capabilities = { 
/**
 * Capabilities found present, sorted for a stable wire representation.
 */
present: Array<Capability>, };
