// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What actually went wrong underneath, preserved so the UI can show it on demand and so a bug
 * report contains something actionable.
 */
export type Cause = { "kind": "os", errno: number | null, description: string, } | { "kind": "command", program: string, status: number | null, stderr: string, } | { "kind": "malformed", source: string, detail: string, } | { "kind": "other", detail: string, };
