// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one thing changed between two samples.
 */
export type Change = { from: number, to: number, 
/**
 * Signed difference. Growth is positive.
 */
delta: number, };
