// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a battery is doing, as the kernel reports it.
 */
export type ChargeState = "charging" | "discharging" | "full" | "not_charging" | "unknown";
