// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { OperationId } from "./OperationId";

/**
 * How an operation ended. Sent as the terminal event so the frontend never has to infer it.
 */
export type Completion = { "outcome": "done", id: OperationId, } | { "outcome": "cancelled", id: OperationId, } | { "outcome": "failed", id: OperationId, error: AppError, };
