// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a package appearing in a removal is worth saying something about.
 *
 * Ordered by how bad it is, so the worst concern in a set decides the [`RemovalRisk`].
 */
export type Concern = "cascade" | "important" | "display_manager" | "running_kernel" | "required" | "essential";
