// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI is given for one tick.
 */
export type CpuReading = { 
/**
 * Overall utilisation, `0.0..=1.0`.
 */
total: number, 
/**
 * Per core, in the kernel's order. Length is however many cores the machine has.
 *
 * Stacer's palette asserted past twenty cores; nothing here is indexed by a fixed-size table.
 */
per_core: Array<number>, 
/**
 * Current frequency of the first core, in kHz, where the platform reports one.
 *
 * `None` on hardware without `cpufreq` — a virtual machine, usually — rather than a zero that
 * would read as "stopped".
 */
frequency_khz: number | null, };
