// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenFile } from "./OpenFile";
import type { ProcessIo } from "./ProcessIo";

/**
 * Everything the detail panel can show about one process.
 */
export type Detail = { pid: number, executable: string | null, working_directory: string | null, 
/**
 * The systemd slice or container this belongs to. Readable for any process.
 */
cgroup: string | null, thread_count: number, io: ProcessIo | null, open_files: Array<OpenFile> | null, 
/**
 * Environment variables. **Never escalated to read**, because another user's environment
 * routinely contains credentials.
 */
environment: Array<[string, string]> | null, 
/**
 * Sum of the sizes of the regular files it has open, plus its executable.
 */
disk_footprint: number | null, 
/**
 * Why parts of this are missing, when they are. Empty when everything was readable.
 */
restricted: Array<string>, };
