// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";

/**
 * Everything useful in a bug report, collected in one place.
 *
 * Deliberately contains no file contents and no paths outside nix's own directories, so it is safe
 * to copy into a public issue.
 */
export type Diagnostics = { core_version: string, kernel: string | null, capabilities: Capabilities, log_dir: string | null, config_dir: string | null, state_dir: string | null, logging_initialised: boolean, };
