// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One directory's size at one moment.
 */
export type DirSample = { path: string, bytes: number, };
