// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskTotals } from "./DiskTotals";

/**
 * What the UI is given for one tick.
 */
export type DiskReading = { 
/**
 * Summed across every real device.
 */
totals: DiskTotals, 
/**
 * Per device, so `MON-3` can break the chart down. Names are the kernel's.
 */
per_device: Array<[string, DiskTotals]>, };
