// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Throughput over the last interval, in bytes per second.
 */
export type DiskTotals = { read_per_second: number, written_per_second: number, };
