// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicateGroup } from "./DuplicateGroup";
import type { DuplicateStats } from "./DuplicateStats";

/**
 * What a completed duplicate search found.
 */
export type DuplicateReport = { groups: Array<DuplicateGroup>, stats: DuplicateStats, 
/**
 * Sum of what keeping one copy of each group would return.
 */
recoverable: number, 
/**
 * Whether the search was stopped early, so a short list is not mistaken for a clean bill.
 */
cancelled: boolean, };
