// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A set of files with identical content.
 */
export type DuplicateGroup = { 
/**
 * Every path in the group. At least two, and each a distinct inode.
 */
paths: Array<string>, 
/**
 * On-disk bytes of one copy.
 */
bytes: number, 
/**
 * What could be reclaimed by keeping one copy: `bytes * (paths.len() - 1)`.
 */
recoverable: number, };
