// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much work duplicate detection did, so the cost is visible rather than guessed at.
 */
export type DuplicateStats = { 
/**
 * Files that reached stage one.
 */
considered: number, 
/**
 * Files whose size was shared with at least one other.
 */
size_matched: number, 
/**
 * Files whose first 4 KiB were hashed.
 */
heads_hashed: number, 
/**
 * Files read in full.
 */
fully_hashed: number, 
/**
 * Pairs compared byte for byte.
 */
pairs_verified: number, };
