// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * One journal entry.
 */
export type Entry = { 
/**
 * Microseconds since the epoch.
 */
at_us: number, message: string, severity: Severity, 
/**
 * What wrote it — usually the executable's name.
 */
identifier: string, pid: number | null, 
/**
 * An opaque position in the journal, for asking what has appeared since.
 */
cursor: string, };
