// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable, machine-readable failure classes.
 *
 * These strings cross the IPC boundary and may be branched on by the frontend, so they are API:
 * rename one and you break a caller. Add variants freely; change them deliberately.
 */
export type ErrorCode = "cancelled" | "auth_denied" | "helper_unavailable" | "helper_rejected" | "not_found" | "permission_denied" | "io" | "parse" | "unsupported" | "command_failed" | "version_mismatch" | "invalid_input" | "refused" | "internal";
