// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing to match.
 */
export type FileKind = "file" | "directory" | "symlink";
