// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Accounting } from "./Accounting";

/**
 * One mounted filesystem.
 */
export type Filesystem = { 
/**
 * Where it is mounted.
 */
mount_point: string, 
/**
 * Backing device, as the kernel reports it.
 */
device: string, 
/**
 * Filesystem type, e.g. `ext4`, `btrfs`.
 */
fs_type: string, 
/**
 * Total bytes.
 */
total: number, 
/**
 * Bytes in use.
 */
used: number, 
/**
 * Bytes available **to this user** — which is less than free space when a reserve is set.
 */
available: number, 
/**
 * Mounted read-only.
 */
read_only: boolean, 
/**
 * Not real storage: tmpfs, squashfs, overlay and friends.
 */
pseudo: boolean, 
/**
 * How much to trust the figures above.
 */
accounting: Accounting, 
/**
 * Device id, so the scanner can avoid crossing filesystem boundaries.
 */
device_id: number, };
