// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Concern } from "./Concern";

/**
 * One package in a removal, and why it is worth mentioning.
 */
export type Flagged = { package: string, concern: Concern, };
