// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of apt's two formats a file uses.
 */
export type Format = "one_line" | "deb822";
