// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Change } from "./Change";

/**
 * What grew, and by how much, over a window.
 */
export type GrowthReport = { 
/**
 * `None` when fewer than two samples fall in the window: a trend needs two points, and reporting
 * growth from one is arithmetic on a number that does not exist.
 */
total: Change | null, 
/**
 * Directories that changed, largest growth first.
 */
directories: Array<[string, Change]>, };
