// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileKind } from "./FileKind";

/**
 * One result.
 */
export type Hit = { path: string, 
/**
 * Size in bytes, and **zero for a directory**.
 *
 * A directory's own `st_size` is a filesystem artefact — 4,096 on ext4 whether it holds two
 * entries or two hundred — and reporting it as a size means a `min_bytes` filter of 1 KB matches
 * every directory on the machine. This project has already shipped that mistake once, reporting a
 * 9.8 GiB cache as 4 KB by taking a directory's inode size as its contents
 * (`docs/issues/03-reclaim-pipeline.md`), so directories are counted here and never measured —
 * the same rule as [`crate::pkg::measure_paths`].
 */
bytes: number, kind: FileKind, 
/**
 * Modified time, seconds since the epoch. `None` when the filesystem does not report one.
 */
modified: number | null, uid: number, 
/**
 * Permission bits, for display as an octal mode.
 */
mode: number, };
