// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostLine } from "./HostLine";

/**
 * The whole file: its lines, and the bytes they came from.
 */
export type HostsFile = { lines: Array<HostLine>, 
/**
 * The file exactly as it was read.
 *
 * Carried so a write can be a compare-and-swap against it. Also what makes the round-trip test
 * possible, which is the guarantee that nothing is lost.
 */
original: string, };
