// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKind } from "./LineKind";

/**
 * One line of the hosts file.
 */
export type HostLine = { 
/**
 * Position in the file, from zero. Stable for as long as the document is not re-parsed, and what
 * edits address — never the text of the line, which is the mistake that makes a UI act on the
 * wrong row.
 */
id: number, kind: LineKind, 
/**
 * The line as it was read, without its newline. Emitted verbatim unless the line was edited.
 */
raw: string, 
/**
 * The address, for an entry.
 */
ip: string | null, 
/**
 * The names an entry maps to. The first is the canonical name; the rest are aliases.
 */
names: Array<string>, 
/**
 * A trailing `# …` comment on an entry, without the `#`.
 */
comment: string | null, 
/**
 * Whether an entry is in effect. `false` for one that is commented out.
 *
 * Always `true` for the other kinds, which have no such notion.
 */
enabled: boolean, 
/**
 * Whether this line has been changed since it was read, and so must be re-rendered rather than
 * emitted verbatim.
 */
edited: boolean, };
