// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One interface's throughput over the last interval.
 */
export type InterfaceReading = { name: string, received_per_second: number, sent_per_second: number, 
/**
 * Backed by hardware. Only these are summed into the totals.
 */
physical: boolean, };
