// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One interface's throughput and link state over the last interval.
 */
export type InterfaceReading = { name: string, received_per_second: number, sent_per_second: number, 
/**
 * Backed by hardware. Only these are summed into the totals.
 */
physical: boolean, 
/**
 * `up`, `down` or `unknown` — the kernel's own word. `MON-7`.
 */
operstate: string, 
/**
 * Whether a cable or association is actually present, which is not the same as being `up`.
 */
carrier: boolean, 
/**
 * Link speed in megabits, where the driver reports one. Wireless drivers generally do not, and
 * that is `None` rather than a link running at 0 Mb/s.
 */
speed_mbps: number | null, mac: string | null, mtu: number | null, 
/**
 * IPv6 addresses, from `/proc/net/if_inet6`.
 *
 * **IPv4 is deliberately absent.** There is no per-interface IPv4 address anywhere in `sysfs` or
 * `procfs`. Getting one means `getifaddrs` or an `rtnetlink` conversation — the first needs
 * `libc`, the second hand-built netlink messages, and so either `unsafe` or a new dependency in a
 * program that ships privileged code. Showing what is genuinely available and naming what is
 * missing beats quietly presenting an incomplete list called "addresses".
 */
ipv6: Array<string>, };
