// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

/**
 * What happened to one item.
 */
export type ItemOutcome = { "outcome": "reclaimed", id: number, path: string, bytes: number, } | { "outcome": "trashed", id: number, path: string, 
/**
 * Bytes now sitting in the trash, waiting to be emptied.
 */
bytes: number, } | { "outcome": "skipped", id: number, path: string, reason: string, } | { "outcome": "failed", id: number, path: string, error: AppError, };
