// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Load averages, straight from `/proc/loadavg`.
 *
 * The one metric that needs no delta: the kernel already averages it.
 */
export type LoadReading = { one: number, five: number, fifteen: number, 
/**
 * Tasks currently runnable.
 */
running: number, 
/**
 * Tasks in total.
 */
total: number, };
