// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from "./Format";

/**
 * Where an entry lives, precisely enough to edit it without searching for its text.
 */
export type Location = { file: string, format: Format, 
/**
 * For [`Format::OneLine`], the zero-based line. For [`Format::Deb822`], the zero-based stanza.
 */
index: number, };
