// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Package managers whose cache the helper can clean.
 */
export type Manager = "apt" | "dnf" | "pacman" | "zypper";
