// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What walking a package's own file list found on disk.
 *
 * Both figures, because they answer different questions and the difference between them is the
 * interesting part. See the module documentation for why neither is compared against
 * [`Package::recorded_bytes`].
 */
export type Measured = { 
/**
 * Bytes the files contain — the sum of their lengths.
 */
apparent_bytes: number, 
/**
 * Bytes the filesystem has committed, from each file's allocated block count.
 *
 * **This is what removing the package gives back**, and it is the larger of the two for any
 * package of small files: a 200-byte icon still costs a 4 KiB block. It can also be *smaller*
 * than `apparent_bytes` for a sparse or transparently compressed file, which is why it is
 * measured rather than derived by rounding.
 */
disk_bytes: number, 
/**
 * Regular files counted, each distinct inode once.
 */
files: number, 
/**
 * Directories in the file list, which are **not** counted.
 *
 * A package's directories are almost always shared with other packages — `/usr/bin` belongs to
 * no one — so attributing their bytes here would double-count across the inventory. Reported so
 * the figure is legible rather than silently narrower than the file list.
 */
directories: number, 
/**
 * Paths dpkg lists that could not be read.
 *
 * Non-zero means the figure is a floor, not a total: a diverted file, a path removed behind
 * dpkg's back, or a directory this user cannot traverse. Surfaced rather than folded into the
 * count, so an understated total is visible as one (§P7).
 */
unreadable: number, };
