// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Memory as `free` would report it, in bytes.
 */
export type MemoryReading = { total: number, 
/**
 * In use: total, less free, less what the caches would give back.
 */
used: number, 
/**
 * Genuinely unallocated. Almost always small on a healthy machine, and not the useful figure.
 */
free: number, 
/**
 * What could be given to a new process without swapping. **The figure that matters.**
 */
available: number, 
/**
 * Buffers plus page cache plus reclaimable slab, as `free` groups them.
 */
buffers_cache: number, 
/**
 * Shared memory, which is counted inside the cache figure rather than beside it.
 */
shared: number, swap_total: number, swap_used: number, swap_free: number, };
