// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a rule watches.
 *
 * Typed rather than a string, so a rule cannot name a metric that does not exist and the UI can
 * enumerate what is available.
 */
export type Metric = { "metric": "cpu_usage" } | { "metric": "memory_pressure" } | { "metric": "swap_pressure" } | { "metric": "disk_usage", mount: string, } | { "metric": "disk_space_remaining", mount: string, } | { "metric": "temperature" };
