// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a name pattern is interpreted.
 */
export type NameMatch = "contains" | "glob" | "regex";
