// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterfaceReading } from "./InterfaceReading";

/**
 * What the UI is given for one tick.
 */
export type NetReading = { 
/**
 * Summed across **physical** interfaces only, so each byte is counted once.
 */
received_per_second: number, sent_per_second: number, 
/**
 * Every interface, physical or not, biggest first.
 */
interfaces: Array<InterfaceReading>, };
