// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file a process has open.
 */
export type OpenFile = { 
/**
 * The file descriptor number.
 */
fd: number, 
/**
 * Where it points. A socket or pipe appears as `socket:[…]`, which is the kernel's own notation.
 */
target: string, 
/**
 * Size in bytes, for the ones that are real files.
 */
bytes: number | null, };
