// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manager } from "./Manager";
import type { Measured } from "./Measured";

/**
 * One installed package.
 */
export type Package = { 
/**
 * The package's identity, arch-qualified where the manager qualifies: `libc6:amd64`.
 *
 * **Derived from `name` and `arch`, and a real field rather than a method on purpose.** Methods
 * do not cross into TypeScript — `docs/issues/02-rust-typescript-boundary.md` §5 is a defect from
 * exactly that — and the alternative was the frontend rebuilding the rule in its own language,
 * where it could drift. Computed once, in [`Package::new`].
 */
id: string, name: string, 
/**
 * Architecture, as the manager qualifies it — `amd64`, `i386`, `all`.
 *
 * Empty for managers with no such concept. **Not cosmetic:** this machine has 41 packages
 * installed for two architectures at once, so `name` alone is not an identity. Use
 * [`Package::id`].
 */
arch: string, version: string, 
/**
 * One-line description, as the manager holds it.
 */
summary: string, 
/**
 * Size the package database records, in bytes.
 *
 * Fast, and what the manager itself believes — which for dpkg is a **build-time estimate**, not
 * a measurement of this disk. See the module documentation.
 */
recorded_bytes: number, 
/**
 * What walking the files found, when the user has asked for it.
 *
 * Never overwrites [`Package::recorded_bytes`]; the two are different metrics and conflating
 * them is the mistake the module documentation records.
 */
measured: Measured | null, 
/**
 * When the package was last installed or upgraded, in seconds since the epoch.
 *
 * **Last changed, not first installed** — dpkg keeps no install date, so this is the mtime of
 * the package's file list, which is rewritten on every upgrade. Named for what it is.
 */
changed_at: number | null, 
/**
 * Whether the user asked for this, as opposed to it arriving as a dependency.
 */
explicit: boolean, manager: Manager, };
