// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manager } from "./Manager";

/**
 * One installed package.
 */
export type Package = { name: string, version: string, 
/**
 * Size the package database records, in bytes. Fast, and what the manager itself believes.
 */
recorded_bytes: number, 
/**
 * Size measured by walking the package's files, when the user has asked for it.
 *
 * Never overwrites [`Package::recorded_bytes`]: the difference between them is post-install
 * growth, and collapsing the two would hide it.
 */
measured_bytes: number | null, 
/**
 * Whether the user asked for this, as opposed to it arriving as a dependency.
 */
explicit: boolean, manager: Manager, };
