// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";

/**
 * A page of entries plus where to resume.
 */
export type Page = { entries: Array<Entry>, 
/**
 * The last entry's cursor, to pass back for the next poll. `None` when nothing was returned, in
 * which case the caller keeps the cursor it already had.
 */
cursor: string | null, };
