// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Battery } from "./Battery";

/**
 * Mains and batteries together.
 */
export type PowerReading = { 
/**
 * Whether a mains supply reports itself online. `None` when there is no mains supply at all,
 * which is how a desktop with no `AC` node looks and is different from "unplugged".
 */
on_mains: boolean | null, 
/**
 * Empty on a desktop. `MON-5` hides the whole panel then rather than showing an empty one.
 */
batteries: Array<Battery>, };
