// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReclaimMethod } from "./ReclaimMethod";
import type { Reclaimable } from "./Reclaimable";
import type { Safety } from "./Safety";

/**
 * One thing the preview proposes to reclaim.
 */
export type PreviewItem = { 
/**
 * Stable across a preview, used to select a subset.
 */
id: number, path: string, 
/**
 * What the user sees.
 */
label: string, 
/**
 * Bytes expected back. Always the on-disk figure, never the apparent size.
 */
bytes: number, safety: Safety, method: ReclaimMethod, 
/**
 * What this costs, when it costs something. `Review` items must have one.
 */
cost: string | null, 
/**
 * The category that proposed it.
 */
category: string, 
/**
 * How much of `bytes` will actually come back.
 *
 * [`Reclaimable::Exact`] for the ordinary case. On a copy-on-write filesystem where extents may
 * be shared with a snapshot this is qualified, and the UI must show the caveat beside the size
 * rather than presenting the number bare.
 */
reclaimable: Reclaimable, 
/**
 * Size at preview time, so execution can detect a change underneath it.
 */
fingerprint: number, };
