// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewItem } from "./PreviewItem";
import type { Refusal } from "./Refusal";
import type { Ticket } from "./Ticket";

/**
 * What would happen, computed before anything does.
 */
export type Preview = { ticket: Ticket, items: Array<PreviewItem>, 
/**
 * Total if everything offered were reclaimed, taking every stated size at face value.
 */
total_bytes: number, 
/**
 * The part of [`Preview::total_bytes`] nix is willing to **promise**.
 *
 * Lower than the total whenever some entry sits on a copy-on-write filesystem and its
 * exclusivity could not be proven. Those entries contribute nothing here, because a total is a
 * promise and a promise assembled from maybes is not one. When the two figures differ, the UI
 * must lead with this one.
 */
promisable_bytes: number, 
/**
 * Total of only the entries safe enough to pre-check.
 */
safe_bytes: number, 
/**
 * Things a category proposed that the protection rules refused. Shown, not hidden: a user
 * should be able to see that nix declined to touch something.
 */
refused: Array<Refusal>, };
