// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewItem } from "./PreviewItem";
import type { Refusal } from "./Refusal";
import type { Ticket } from "./Ticket";

/**
 * What would happen, computed before anything does.
 */
export type Preview = { ticket: Ticket, items: Array<PreviewItem>, 
/**
 * Total if everything offered were reclaimed.
 */
total_bytes: number, 
/**
 * Total of only the entries safe enough to pre-check.
 */
safe_bytes: number, 
/**
 * Things a category proposed that the protection rules refused. Shown, not hidden: a user
 * should be able to see that nix declined to touch something.
 */
refused: Array<Refusal>, };
