// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessState } from "./ProcessState";

/**
 * One process, as the table shows it.
 */
export type Process = { pid: number, ppid: number, 
/**
 * The executable's own name, from `comm`. Truncated to fifteen characters by the kernel.
 */
name: string, 
/**
 * The full command line, or the name in brackets for a kernel thread — which is what `ps` does,
 * and it distinguishes "no arguments" from "not a userspace process at all".
 */
command: string, state: ProcessState, uid: number, 
/**
 * Resolved from `/etc/passwd`, or the uid as text when it has no entry — a container's uid, say.
 */
user: string, 
/**
 * Percentage of **one core**, as `top` reports it. Can exceed 100 for a threaded process.
 */
cpu_percent: number, 
/**
 * Resident set size: physical memory actually held.
 */
memory_bytes: number, threads: number, 
/**
 * The kernel's start time in clock ticks since boot. Part of a process's identity, not a display
 * field: with the pid it survives pid reuse.
 */
started_ticks: number, };
