// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a process is doing, as the kernel's single letter.
 */
export type ProcessState = "running" | "sleeping" | "disk_sleep" | "stopped" | "zombie" | "idle" | "other";
