// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bytes a process has moved, from `/proc/<pid>/io`.
 */
export type ProcessIo = { 
/**
 * Bytes read through syscalls, whether or not they touched a disk.
 */
read_chars: number, written_chars: number, 
/**
 * Bytes that actually came from a block device. Zero for a process working entirely from cache,
 * which is why both figures are shown: they answer different questions.
 */
read_bytes: number, written_bytes: number, };
