// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId";

/**
 * A progress report. `total` is optional because a streaming scan does not know its size up front,
 * and claiming one would be dishonest.
 */
export type Progress = { id: OperationId, 
/**
 * Units completed. Units are operation-specific; the label says what they are.
 *
 * Crosses the wire as a JavaScript number rather than a `bigint`: a double holds integers
 * exactly to 2^53, which is nine quadrillion files. Nothing we count will reach it, and
 * `bigint` would make every arithmetic site in the frontend awkward for no benefit.
 */
done: number, 
/**
 * Total units, when genuinely known.
 */
total: number | null, 
/**
 * What is happening right now, phrased for a user.
 */
message: string | null, };
