// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a container prune covers. `STO-13`.
 */
export type PruneScope = "dangling_images" | "unused_images" | "stopped_containers" | "build_cache";
