// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileKind } from "./FileKind";
import type { NameMatch } from "./NameMatch";

/**
 * One search.
 */
export type Query = { root: string, 
/**
 * The name pattern. An empty pattern matches everything, so the other filters can stand alone.
 */
name: string, match_kind: NameMatch, 
/**
 * Match on the whole path rather than the file name.
 */
whole_path: boolean, case_sensitive: boolean, min_bytes: number | null, max_bytes: number | null, 
/**
 * Modified at or after this many seconds since the epoch.
 */
modified_after: number | null, modified_before: number | null, kind: FileKind | null, 
/**
 * Owner, by numeric uid.
 */
owner_uid: number | null, 
/**
 * Permission bits that must all be set — `0o111` for "executable by someone".
 */
mode_all_of: number | null, 
/**
 * Empty files and directories only.
 *
 * "Empty" means no bytes for a file and **no entries** for a directory — different questions, and
 * a directory's `st_size` answers neither.
 */
empty_only: boolean, 
/**
 * **Invert the match**, and actually invert it.
 */
invert: boolean, cross_filesystems: boolean, 
/**
 * Stop after this many matches. `None` means no cap, which is the default.
 */
limit: number | null, };
