// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuReading } from "./CpuReading";
import type { DiskReading } from "./DiskReading";
import type { LoadReading } from "./LoadReading";
import type { MemoryReading } from "./MemoryReading";
import type { NetReading } from "./NetReading";

/**
 * One tick: every metric family, sampled at the same moment.
 */
export type Reading = { 
/**
 * Seconds since the Unix epoch.
 */
at: number, cpu: CpuReading, memory: MemoryReading, load: LoadReading, disk: DiskReading, network: NetReading, };
