// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A category of reclaimable system file.
 *
 * Each names a fixed set of roots inside the helper. Adding a variant means widening the privileged
 * surface, and belongs in the same review as the feature that needs it.
 */
export type ReclaimKind = "package_cache" | "rotated_log" | "crash_dump";
