// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of an entry's size would actually come back if it were reclaimed.
 *
 * On a copy-on-write filesystem — btrfs, ZFS, or an LVM thin pool — a file's extents may be shared
 * with a snapshot. Deleting the file removes the name, but the blocks stay allocated until every
 * reference to them is gone, so the space does **not** come back. A tool that reports the file's
 * size as reclaimable in that situation is promising something it cannot deliver.
 *
 * So the estimate is qualified rather than asserted. Specification `STO-17`: *where exclusive size
 * is unobtainable, suppress the estimate rather than fake it.*
 */
export type Reclaimable = { "confidence": "exact" } | { "confidence": "at_most", exclusive: number | null, reason: string, } | { "confidence": "unknown", reason: string, };
