// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manager } from "./Manager";
import type { ReclaimKind } from "./ReclaimKind";
import type { RemovableKind } from "./RemovableKind";
import type { VacuumLimit } from "./VacuumLimit";

/**
 * How space is actually reclaimed. Always prefers the owning tool over `unlink`.
 */
export type ReclaimMethod = { "method": "package_manager", manager: Manager, } | { "method": "journal_vacuum", limit: VacuumLimit, } | { "method": "packages", kind: RemovableKind, names: Array<string>, } | { "method": "system_file", kind: ReclaimKind, path: string, } | { "method": "snap_revision", package: string, revision: string, } | { "method": "container_prune", scope: string, } | { "method": "trash_empty", volume: string, } | { "method": "move_to_trash", path: string, } | { "method": "unlink", path: string, };
