// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a path may not be reclaimed.
 */
export type Refusal = { path: string, 
/**
 * Stable rule identifier.
 */
rule: string, 
/**
 * Phrased for a user.
 */
reason: string, };
