// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flagged } from "./Flagged";
import type { RemovalRisk } from "./RemovalRisk";

/**
 * What removing a set of packages would actually do.
 */
export type RemovalPreview = { 
/**
 * What the user selected, so the cascade is the difference rather than a guess.
 */
requested: Array<string>, 
/**
 * Packages that would be removed, including any pulled out as a consequence.
 */
removing: Array<string>, 
/**
 * Bytes the manager expects to free.
 */
freed_bytes: number, 
/**
 * Packages the manager would *install or upgrade* to satisfy the removal.
 *
 * Almost always empty, and alarming when it is not — worth surfacing rather than hiding.
 */
installing: Array<string>, 
/**
 * Everything worth saying about the packages involved, worst first.
 */
flagged: Array<Flagged>, 
/**
 * The worst concern, as one value.
 */
risk: RemovalRisk, };
