// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What removing a set of packages would actually do.
 */
export type RemovalPreview = { 
/**
 * Packages that would be removed, including any pulled out as a consequence.
 */
removing: Array<string>, 
/**
 * Bytes the manager expects to free.
 */
freed_bytes: number, 
/**
 * Packages the manager would *install or upgrade* to satisfy the removal.
 *
 * Almost always empty, and alarming when it is not — worth surfacing rather than hiding.
 */
installing: Array<string>, };
