// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A class of removable package.
 *
 * Like [`ReclaimKind`], this names a derivation the privileged helper performs **itself**. Adding a
 * variant widens the privileged surface and belongs in the same review as the feature that needs it.
 */
export type RemovableKind = "old_kernel" | "residual_config";
