// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How bad a removal is, in one value the UI can key on.
 */
export type RemovalRisk = "safe" | "cascading" | "dangerous" | "refused";
