// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a removal actually did, checked against the package database afterwards.
 *
 * # Why this is measured rather than reported
 *
 * `apt-get remove` is one transaction and exits zero or non-zero for the whole thing, so its status
 * says nothing about individual packages. `PKG-2`'s criterion is that **the preview matches the
 * actual outcome**, and the only way to know that is to look: the inventory is re-read afterwards and
 * diffed against what the preview said would happen.
 *
 * This is the same discipline as the reclaim pipeline's `Report`, and it exists for the same reason —
 * an operation that reports what it *intended* is how a tool ends up claiming to have freed space it
 * did not free.
 */
export type RemovalOutcome = { 
/**
 * Packages that are no longer installed, of those the preview said would go.
 */
removed: Array<string>, 
/**
 * Packages the preview said would go that are **still installed**.
 *
 * Not necessarily a failure — apt can decline part of a transaction — but never something to
 * report as success.
 */
remaining: Array<string>, 
/**
 * Packages that went that the preview did **not** mention.
 *
 * Should always be empty. If it is not, the preview the user approved was not the operation that
 * ran, which is worth knowing loudly rather than never.
 */
unexpected: Array<string>, 
/**
 * Bytes the manager expected to free. Still an expectation — see `Report::freed` for why nix does
 * not claim a measured figure it has not measured.
 */
expected_freed_bytes: number, };
