// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Location } from "./Location";

/**
 * One repository, as apt would read it.
 */
export type Repository = { at: Location, 
/**
 * Whether apt uses this. A commented-out line, or `Enabled: no` in deb822.
 */
enabled: boolean, 
/**
 * `deb`, `deb-src`, or both for a deb822 stanza that lists both.
 */
types: Array<string>, uris: Array<string>, 
/**
 * The suite or codename: `jammy`, `stable`, `jammy-updates`.
 */
suites: Array<string>, components: Array<string>, 
/**
 * `arch=` in the one-line options, or `Architectures:` in deb822.
 */
architectures: Array<string>, 
/**
 * The keyring that signs this repository.
 *
 * First-class rather than buried in an options string: it is the difference between a repository
 * apt will trust and one it will refuse, and it is the field most likely to be wrong after a
 * manual edit.
 */
signed_by: string | null, 
/**
 * Options this module does not model, kept so they can be shown and are never dropped.
 */
other_options: Array<string>, 
/**
 * A human label, from deb822's `X-Repolib-Name` where present.
 */
label: string | null, 
/**
 * The entry as it appears in the file, for display.
 */
text: string, };
