// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemOutcome } from "./ItemOutcome";

/**
 * The per-item account of what was done.
 */
export type Report = { outcomes: Array<ItemOutcome>, 
/**
 * Sum of what was actually removed. **Excludes anything moved to the trash**, which is still on
 * the filesystem and so has not been freed.
 */
freed: number, 
/**
 * Sum of what was moved to the trash: recoverable, and not yet freed.
 *
 * Reported separately rather than added to [`Report::freed`] because the trash is on the same
 * filesystem as its contents by necessity, so trashing changes free space by nothing. Emptying
 * the trash is what reclaims it, and the UI says so whenever this is non-zero.
 */
trashed: number, 
/**
 * Change in the filesystem's used bytes, measured independently before and after.
 *
 * This is how the specification's "within 2%" criterion is *checked* rather than asserted: nix
 * compares its own arithmetic against what the filesystem says actually happened.
 */
measured_delta: number | null, 
/**
 * Whether the two agree closely enough to be reported as accurate.
 */
measurement_agrees: boolean | null, cancelled: boolean, 
/**
 * Counts, carried as fields rather than computed in the frontend so the classification lives
 * in one place and the UI cannot disagree with the backend about what happened.
 */
reclaimed_count: number, skipped_count: number, failed_count: number, };
