// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A package left behind in a removed-but-configured state.
 *
 * Debian keeps configuration for a package removed without `--purge`. Small individually,
 * substantial in aggregate, and genuinely dead weight.
 */
export type ResidualConfig = { name: string, bytes: number, };
