// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metric } from "./Metric";

/**
 * One threshold a user has asked to be told about.
 */
export type Rule = { metric: Metric, 
/**
 * The value at which it fires. A fraction for the usage metrics, bytes for free space, degrees
 * for temperature — the metric decides the unit.
 */
threshold: number, 
/**
 * How far back the value must come before the rule is considered clear.
 *
 * Zero would mean a value sitting on the threshold fires every time it wobbles.
 */
hysteresis: number, 
/**
 * Seconds after clearing during which it will not fire again.
 */
cooldown_seconds: number, 
/**
 * Off means silent **immediately**, which the specification requires: a disabled rule that
 * delivers one more notification is a disabled rule the user does not believe.
 */
enabled: boolean, };
