// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How safe it is to reclaim an entry.
 *
 * **Computed, never hardcoded per category**: an open file handle, a recent access time, or a
 * protected-path match escalates the rating.
 */
export type Safety = "safe" | "review" | "risky" | "never";
