// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { DirSample } from "./DirSample";

/**
 * One observation of where the space was.
 *
 * Named `Sample` rather than `Snapshot` because [`crate::cow::Snapshot`] is a filesystem snapshot and
 * means something entirely different. Two exported types sharing a name silently overwrote each
 * other's TypeScript binding once already.
 */
export type Sample = { 
/**
 * Seconds since the Unix epoch.
 */
at: number, 
/**
 * On-disk bytes across everything scanned.
 */
total_allocated: number, 
/**
 * Per-category totals. A list rather than a map, so its order is stable on the wire.
 */
by_category: Array<[Category, bigint]>, 
/**
 * The largest directories, biggest first. Bounded by the caller.
 */
top_directories: Array<DirSample>, };
