// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing that went wrong, attributed to the path it happened at.
 *
 * Collected rather than propagated: a scan with unreadable corners is a *partial* result, which is
 * useful, not a failure, which is not.
 */
export type ScanError = { path: string, message: string, };
