// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanError } from "./ScanError";
import type { SpaceTree } from "./SpaceTree";

/**
 * What a completed scan produced.
 */
export type ScanResult = { 
/**
 * The tree, capped at [`Options::max_depth`].
 */
tree: SpaceTree, 
/**
 * Files visited, including those only counted towards a parent's total.
 */
files: number, 
/**
 * Directories visited.
 */
dirs: number, 
/**
 * Total apparent bytes.
 */
apparent_size: number, 
/**
 * Total on-disk bytes, with hard links counted once.
 */
allocated: number, 
/**
 * Bytes skipped because they could not be read. Reported so coverage is visible rather than
 * silently missing.
 */
skipped: number, 
/**
 * Per-path failures, capped so a systematically unreadable tree cannot exhaust memory.
 */
errors: Array<ScanError>, 
/**
 * Whether the walk stopped early because it was cancelled.
 */
cancelled: boolean, 
/**
 * Whether [`ScanResult::errors`] was truncated.
 */
errors_truncated: boolean, };
