// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which systemd instance to talk to. `SVC-4`.
 */
export type Scope = "system" | "user";
