// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fan } from "./Fan";
import type { Temperature } from "./Temperature";

/**
 * Everything the hardware reports about heat.
 */
export type SensorReading = { temperatures: Array<Temperature>, 
/**
 * Empty on hardware that reports no fans, which is common and not a fault.
 */
fans: Array<Fan>, };
