// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sample } from "./Sample";

/**
 * A run of samples, with the gaps left in.
 */
export type Series = { 
/**
 * One entry per interval between the first and last sample. `None` where nothing was recorded.
 *
 * **Never interpolated** (§P8). A missing point means the machine was off, on battery, or nix was
 * not running — and putting a plausible number there would turn "we do not know" into something a
 * user might act on.
 */
points: Array<Sample | null>, 
/**
 * Seconds per interval, so the caller can label an axis.
 */
interval: number, 
/**
 * How many intervals have no sample.
 */
gaps: number, };
