// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";
import type { Rule } from "./Rule";
import type { StartView } from "./StartView";
import type { Theme } from "./Theme";

/**
 * Everything nix remembers between runs.
 */
export type Settings = { 
/**
 * Format version of the file this was loaded from.
 */
version: number, theme: Theme, 
/**
 * Stable identifier, not a display name.
 */
start_view: StartView, log_level: LogLevel, 
/**
 * Paths the scanner and executor must never touch, in addition to the built-in set.
 */
protected_paths: Array<string>, 
/**
 * Show pseudo-filesystems (tmpfs, squashfs, overlay) in the filesystem list.
 */
show_pseudo_filesystems: boolean, 
/**
 * Opt-in periodic collection of category totals (`STO-16`). Off by default: it installs a
 * systemd user timer, which is a change to the user's system.
 */
growth_history_enabled: boolean, 
/**
 * Threshold alerts (`MON-6`). Empty by default: a monitoring tool that starts notifying about
 * thresholds nobody chose is one whose notifications get switched off wholesale.
 */
alert_rules: Array<Rule>, 
/**
 * Process-table columns the user has hidden (`PRC-1`).
 *
 * Stored as the columns *hidden* rather than those shown, so a column added by a later version
 * appears by default instead of being invisible until someone finds the setting.
 */
hidden_process_columns: Array<string>, 
/**
 * Show a tray icon, and keep running when the window closes. `PLT-3`.
 *
 * Off by default. A tray icon is a claim on the user's panel and a process that outlives the
 * window they closed, and neither is something to assume they wanted — Stacer had no tray at all,
 * so nobody is losing behaviour they had.
 */
tray_enabled: boolean, 
/**
 * With a tray icon, whether closing the window quits or hides. `PLT-3`.
 *
 * Ignored entirely when [`Settings::tray_enabled`] is false: hiding to a tray that is not there
 * leaves a process with no way back to it, which is the worst of both.
 */
close_to_tray: boolean, };
