// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The signals a task manager has any business sending.
 *
 * Deliberately not an integer. `SIGKILL` is here because sometimes it is the only thing that works,
 * and `SIGTERM` is first in the list because it is what should be tried first.
 */
export type Signal = "term" | "kill" | "hup" | "int" | "stop" | "cont";
