// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";

/**
 * What the host can do, as sent to the frontend.
 */
export type Snapshot = { 
/**
 * Capabilities found present, sorted for a stable wire representation.
 */
present: Array<Capability>, };
