// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CowKind } from "./CowKind";

/**
 * A snapshot or subvolume holding space.
 */
export type Snapshot = { 
/**
 * What the filesystem calls it: a btrfs path, a ZFS dataset name, an LV name.
 */
name: string, 
/**
 * Where it is visible, when it is mounted or reachable.
 */
path: string | null, 
/**
 * Bytes held **only** by this snapshot, when the filesystem can say.
 *
 * This is the figure that would come back if it were deleted. `None` means the filesystem could
 * not tell us, and nix will not guess.
 */
exclusive_bytes: number | null, 
/**
 * Total bytes the snapshot references, most of which it usually shares with the live data.
 */
referenced_bytes: number | null, kind: CowKind, };
