// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryId } from "./EntryId";

/**
 * An arena of entries plus the roots, so the tree can be sent over IPC without cycles.
 */
export type SpaceTree = { 
/**
 * Every entry, keyed by id.
 */
entries: Record<string, SpaceEntry>, 
/**
 * Top-level entries, in insertion order.
 */
roots: Array<EntryId>, };
