// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which view opens on launch. A stable identifier — deliberately not a display name.
 */
export type StartView = "overview" | "explorer" | "reclaim" | "settings";
