// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tier } from "./Tier";

/**
 * What nix found when it looked at the installed units.
 */
export type State = { tier: Tier, 
/**
 * Whether both unit files are present.
 */
installed: boolean, 
/**
 * Whether the timer is enabled.
 */
enabled: boolean, 
/**
 * Present, but not what this version of nix would write.
 *
 * The specification requires an orphan from a previous version to be *detected at startup and
 * repairable*. A unit whose `ExecStart` points at a binary that has moved is a job that fails
 * every day in silence, which is worse than no job at all.
 */
orphaned: boolean, 
/**
 * Where the units live, so a user can look at them.
 */
directory: string | null, };
