// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a search ended.
 */
export type Summary = { examined: number, matched: number, 
/**
 * Directories that could not be entered.
 *
 * Reported rather than ignored: a search of `/` as an ordinary user cannot read everything, and a
 * result set that is quietly partial is worse than one that says so. Stacer's answer to this was
 * to re-run `find` under `sudo`.
 */
unreadable: number, 
/**
 * Whether the cap was reached. `false` unless a limit was asked for.
 */
truncated: boolean, cancelled: boolean, };
