// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One temperature sensor.
 */
export type Temperature = { 
/**
 * The chip, e.g. `coretemp`.
 */
chip: string, 
/**
 * The sensor's own label where it has one, e.g. `Package id 0`.
 */
label: string, celsius: number, 
/**
 * The hardware's own "getting warm" threshold, where it declares one.
 */
high_celsius: number | null, 
/**
 * The hardware's own critical threshold.
 */
critical_celsius: number | null, };
