// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proof that a preview was computed and shown.
 *
 * The only way to obtain one is [`preview`]. It carries the identity of the set it describes, so
 * [`execute`] can refuse a selection the user was never shown.
 */
export type Ticket = number;
