// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How collection can happen on this system.
 */
export type Tier = "timer" | "session";
