// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * A timer's schedule. `SVC-4`.
 */
export type Timer = { name: string, 
/**
 * The unit it starts.
 */
unit: string, 
/**
 * Microseconds since the epoch, or `None` when it will not fire again — a one-shot that has run,
 * or a calendar timer whose condition can no longer be met. `None` rather than zero, because
 * systemd reports both `0` and `u64::MAX` for "never" depending on which property is asked.
 */
next_elapse_us: number | null, 
/**
 * Whether it is scheduled to fire again at all.
 *
 * Separate from [`Timer::next_elapse_us`] because a **monotonic** timer — one using `OnBootSec`
 * or `OnUnitActiveSec` — is genuinely scheduled but has no wall-clock instant to show. Reporting
 * it as "never" would be wrong, and converting its monotonic offset into a date would be an
 * invention.
 */
scheduled: boolean, 
/**
 * Seconds from now until it next fires, for either kind of schedule.
 *
 * The figure a person actually wants, and computable for both without inventing anything: a
 * calendar timer's instant less the wall clock, or a monotonic timer's offset less the current
 * uptime. The monotonic arithmetic is exact because both sides are the same clock — which is why
 * it is done this way rather than by adding the boot time to the offset, a conversion that drifts
 * once a machine has suspended.
 *
 * Negative when a timer is overdue, which happens legitimately while its service is still running.
 */
seconds_until: number | null, last_trigger_us: number | null, scope: Scope, };
