// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One item sitting in a trash directory.
 */
export type TrashedItem = { 
/**
 * Name inside `files/`, which is also the stem of the `.trashinfo`.
 */
name: string, 
/**
 * Where it currently lives.
 */
trashed_path: string, 
/**
 * Where it came from, resolved back to an absolute path.
 */
original_path: string, 
/**
 * When it was trashed, as recorded in the `.trashinfo`.
 */
deleted_at: string, 
/**
 * On-disk bytes.
 */
size: number, };
