// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node of the process tree. `PRC-4`.
 */
export type TreeNode = { pid: number, name: string, 
/**
 * This process alone.
 */
cpu_percent: number, memory_bytes: number, 
/**
 * This process **and everything below it**, which is the figure that explains a slow machine: a
 * build system's cost is spread across dozens of short-lived children, and each one alone looks
 * like nothing.
 */
subtree_cpu_percent: number, subtree_memory_bytes: number, descendants: number, children: Array<TreeNode>, };
