// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * One unit, as `ListUnits` reports it.
 *
 * The field order is the D-Bus signature `(ssssssouso)` and is not rearranged, because the tuple is
 * positional and reordering it silently shifts every value by one.
 */
export type Unit = { 
/**
 * `nginx.service`, `home.mount`, `logrotate.timer`.
 */
name: string, description: string, 
/**
 * Whether systemd could read its definition: `loaded`, `not-found`, `masked`, `bad-setting`.
 */
load_state: string, 
/**
 * `active`, `inactive`, `failed`, `activating`, `deactivating`.
 */
active_state: string, 
/**
 * The finer state: `running`, `exited`, `dead`, `waiting`.
 */
sub_state: string, 
/**
 * The unit this one follows, when it is an alias for another's state.
 */
following: string, 
/**
 * Which manager it came from, so a table can mix both without confusing them.
 */
scope: Scope, };
