// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * A unit file on disk, from `ListUnitFiles`. `SVC-1`.
 *
 * Separate from [`Unit`] because the two answer different questions: `ListUnits` reports what is
 * *loaded*, and a disabled unit that has never run appears in neither its output nor Stacer's.
 */
export type UnitFile = { name: string, 
/**
 * `enabled`, `disabled`, `static`, `masked`, `generated`, `transient`, `indirect`, `alias`.
 */
state: string, scope: Scope, };
