// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much journal to keep. Typed rather than a string so nothing caller-supplied is interpolated
 * into a command line.
 */
export type VacuumLimit = { "by": "size", mebibytes: number, } | { "by": "age", days: number, };
