// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Methuselah Nwodobeh

/**
 * Rolling history charts. `MON-3`.
 *
 * Three things this gets right that Stacer did not:
 *
 * - **Maxima decay.** An axis that only ever grows is flattened permanently by one burst: download a
 *   file at 100 MB/s and every subsequent chart of a 200 KB/s connection is a flat line at the
 *   bottom. The peak here eases back toward whatever is currently visible, so the chart re-scales
 *   once the burst has left the window.
 * - **A palette that works for any core count.** Colours are generated by rotating hue across
 *   however many cores there are. Stacer indexed a fixed table and asserted past twenty.
 * - **Gaps are gaps.** A missing sample breaks the line rather than being bridged, the same rule the
 *   growth history follows.
 *
 * Drawn on a canvas rather than as SVG for the same reason the treemap is: sixty points times eight
 * cores is 480 nodes a second, and a DOM cannot be asked to do that.
 */
import { useEffect, useRef } from "react";

/** One line to draw. `null` marks a gap, which is left as one. */
export type Series = {
  label: string;
  points: Array<number | null>;
  colour: string;
};

/**
 * Colours for `n` series, spread around the wheel.
 *
 * Generated rather than tabulated, so sixty-four cores render as correctly as four. The saturation
 * and lightness are fixed so no core is visually louder than another — the hue carries identity and
 * nothing else does.
 */
export function palette(n: number): string[] {
  if (n <= 0) return [];
  // A golden-angle step spreads adjacent indices far apart, so neighbouring cores are easy to tell
  // apart even when there are many of them. Stepping by 360/n instead makes 64 cores 5.6° apart.
  return Array.from({ length: n }, (_, i) => `hsl(${(i * 137.508) % 360} 62% 55%)`);
}

/** Format a byte-rate axis label in binary units, per §P8. */
export function formatRate(bytes: number): string {
  const units = ["B", "KiB", "MiB", "GiB", "TiB"];
  let value = bytes;
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit += 1;
  }
  return `${value < 10 && unit > 0 ? value.toFixed(1) : Math.round(value)} ${units[unit]}/s`;
}

type Props = {
  series: Series[];
  /** Fixed upper bound, for a percentage axis. Omit to scale to the data. */
  max?: number;
  /** How many slots the x-axis holds, so a partial history draws at the right width. */
  capacity: number;
  height?: number;
  /** Rendered at the top right, usually the current value. */
  caption?: string;
  /** Formats the peak into an axis label. */
  formatPeak?: (value: number) => string;
};

export default function Chart({
  series,
  max,
  capacity,
  height = 90,
  caption,
  formatPeak,
}: Props) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  /**
   * The decaying peak. Held in a ref rather than state: it changes on every frame and nothing about
   * the component's structure depends on it, so re-rendering for it would be pure cost.
   */
  const peakRef = useRef(0);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const context = canvas.getContext("2d");
    if (!context) return;

    const ratio = window.devicePixelRatio || 1;
    const width = canvas.clientWidth;
    canvas.width = Math.max(1, Math.floor(width * ratio));
    canvas.height = Math.max(1, Math.floor(height * ratio));
    context.setTransform(ratio, 0, 0, ratio, 0, 0);
    context.clearRect(0, 0, width, height);

    const style = getComputedStyle(canvas);
    const rule = style.getPropertyValue("--rule").trim() || "#ddd";
    const ink = style.getPropertyValue("--ink-mute").trim() || "#888";

    // The peak eases toward what is actually on screen rather than latching to the highest value
    // ever seen. Rising immediately keeps a spike visible the moment it happens; falling slowly
    // stops the axis twitching between frames.
    const visible = Math.max(
      0,
      ...series.flatMap((s) => s.points.filter((p): p is number => p !== null)),
    );
    const target = max ?? visible;
    peakRef.current = target > peakRef.current ? target : peakRef.current * 0.92 + target * 0.08;
    const peak = Math.max(peakRef.current, max ?? 1, 1);

    // Baseline and midline, so a flat chart still reads as a chart.
    context.strokeStyle = rule;
    context.lineWidth = 1;
    for (const fraction of [0, 0.5, 1]) {
      const y = height - fraction * (height - 2) - 1;
      context.beginPath();
      context.moveTo(0, y);
      context.lineTo(width, y);
      context.stroke();
    }

    const step = width / Math.max(1, capacity - 1);
    for (const line of series) {
      context.strokeStyle = line.colour;
      context.lineWidth = 1.5;
      context.beginPath();
      // Right-aligned, so the newest sample is at the right edge and a partial history grows
      // leftwards into the space rather than stretching to fill it.
      const offset = capacity - line.points.length;
      let drawing = false;
      line.points.forEach((point, i) => {
        if (point === null) {
          // A gap: lift the pen. Bridging it would draw a value nobody observed.
          drawing = false;
          return;
        }
        const x = (offset + i) * step;
        const y = height - (point / peak) * (height - 2) - 1;
        if (drawing) context.lineTo(x, y);
        else context.moveTo(x, y);
        drawing = true;
      });
      context.stroke();
    }

    if (formatPeak) {
      context.fillStyle = ink;
      context.font = "10px system-ui, sans-serif";
      context.fillText(formatPeak(peak), 4, 11);
    }
  }, [series, max, capacity, height, formatPeak]);

  return (
    <div className="chart">
      {caption && <span className="chart-caption">{caption}</span>}
      <canvas ref={canvasRef} style={{ width: "100%", height }} />
    </div>
  );
}
