#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Methuselah Nwodobeh
"""
Collect third-party attribution from the crates actually in the lockfile. `PLT-5`.

Apache-2.0 §4(d) requires that any NOTICE file a dependency ships be reproduced in distributions.
Most Rust crates carry none, so the honest way to find out is to look rather than to assume — which
is the whole point of this script existing instead of a sentence saying "probably empty".

Reads `Cargo.lock`, finds each package in the local registry, and collects its NOTICE and licence
files. Emits Markdown on stdout.

Run: `python3 scripts/collect-notices.py > THIRD-PARTY-NOTICES.md`
"""
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCK = ROOT / "src-tauri" / "Cargo.lock"

# Our own crates are not third-party.
OURS = {"nix-app", "nix-core", "nix-helper"}

NOTICE_NAMES = ("NOTICE", "NOTICE.md", "NOTICE.txt", "NOTICE-APACHE")


def registry_dirs():
    home = Path(os.environ.get("CARGO_HOME", Path.home() / ".cargo"))
    src = home / "registry" / "src"
    return sorted(src.glob("*")) if src.exists() else []


def packages():
    if not LOCK.exists():
        sys.exit(f"no lockfile at {LOCK}")
    text = LOCK.read_text()
    found = re.findall(
        r'\[\[package\]\]\nname = "([^"]+)"\nversion = "([^"]+)"(?:\nsource = "([^"]*)")?',
        text,
    )
    # Only packages from a registry: a path dependency is one of ours, and a git dependency would
    # need its own handling rather than being silently skipped.
    return [(n, v, s) for (n, v, s) in found if n not in OURS]


def find_source(name, version):
    for base in registry_dirs():
        candidate = base / f"{name}-{version}"
        if candidate.is_dir():
            return candidate
    return None


def main():
    found_notices = []
    missing_source = []
    licences = {}
    total = 0

    for name, version, source in packages():
        total += 1
        if not source:
            # A path dependency that is not ours would be a vendored crate; there are none.
            continue
        directory = find_source(name, version)
        if directory is None:
            missing_source.append(f"{name} {version}")
            continue

        for notice_name in NOTICE_NAMES:
            path = directory / notice_name
            if path.is_file():
                body = path.read_text(errors="replace").strip()
                if body:
                    found_notices.append((name, version, notice_name, body))

        for licence in sorted(directory.glob("LICEN[SC]E*")) + sorted(directory.glob("COPYING*")):
            if licence.is_file():
                licences.setdefault(name, []).append(licence.name)

    out = []
    out.append("<!-- SPDX-License-Identifier: GPL-3.0-or-later -->")
    out.append("<!-- Generated by scripts/collect-notices.py — do not edit by hand. -->")
    out.append("")
    out.append("# Third-party notices")
    out.append("")
    out.append(
        "nix is GPL-3.0-or-later. Its dependencies are permissive, which is compatible in that "
        "direction — but Apache-2.0 §4(d) requires that any `NOTICE` file a dependency ships be "
        "reproduced in distributions, so this file exists to satisfy that rather than to assume it "
        "empty."
    )
    out.append("")
    out.append(f"Generated from `src-tauri/Cargo.lock`: **{total} third-party crates**.")
    out.append("")

    if missing_source:
        out.append(
            "> Some crates were not present in the local registry when this was generated, so their "
            "notices could not be checked. Run `cargo fetch` and regenerate before a release."
        )
        out.append("")
        for entry in missing_source[:20]:
            out.append(f"> - {entry}")
        if len(missing_source) > 20:
            out.append(f"> - …and {len(missing_source) - 20} more")
        out.append("")

    out.append("## NOTICE files")
    out.append("")
    if found_notices:
        out.append(
            f"{len(found_notices)} of the {total} crates ship a `NOTICE`. Reproduced in full below, "
            "as §4(d) requires."
        )
        out.append("")
        for name, version, filename, body in sorted(found_notices):
            out.append(f"### {name} {version} — `{filename}`")
            out.append("")
            out.append("```")
            out.append(body)
            out.append("```")
            out.append("")
    else:
        out.append(
            "**None.** No crate in the dependency tree ships a `NOTICE` file, so §4(d) imposes no "
            "reproduction requirement. This was checked, not assumed — the check is "
            "`scripts/collect-notices.py`, and re-running it is how the claim stays true."
        )
        out.append("")

    out.append("## Licences")
    out.append("")
    out.append(
        f"{len(licences)} crates ship their licence text in-tree. The licences themselves are the "
        "standard MIT, Apache-2.0, BSD and Unicode texts; the copyright lines they carry are the part "
        "that varies, and are preserved in each crate's own source as distributed."
    )
    out.append("")
    for name in sorted(licences):
        out.append(f"- `{name}`: {', '.join(sorted(set(licences[name])))}")

    print("\n".join(out))


if __name__ == "__main__":
    main()
