// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Methuselah Nwodobeh

/**
 * Harvest Stacer's Qt `.ts` translation files into JSON. `PLT-1`.
 *
 * Stacer shipped 26 locales, each around 250 translated messages, contributed over years by people who
 * are not going to do it again for a new project. Restarting from an empty catalogue would throw that
 * away. The spec asks for them harvested rather than rewritten, and this does it.
 *
 * # What this can and cannot give
 *
 * Keyed on the **English source string**, which is the only stable identity a Qt `.ts` file offers.
 * That means a translation is inherited exactly when nix uses the same English text Stacer did — so
 * the yield is high for interface vocabulary (`Cancel`, `Remove`, `Settings`, `Search`) and zero for
 * anything nix words differently, which is most of its explanatory copy.
 *
 * The script reports the overlap rather than claiming a coverage figure. A catalogue that says it has
 * 251 strings when 30 of them are reachable is worse than one that says 30.
 *
 * Run: `node scripts/harvest-locales.mjs`
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, basename } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "..", "Stacer-native", "translations");
const out = join(here, "..", "src", "locales");

if (!existsSync(source)) {
  console.error(`no Stacer translations at ${source} — nothing to harvest`);
  process.exit(0);
}

/** Undo the XML entities Qt writes. Deliberately minimal: these are the five that appear. */
function unescape(text) {
  return text
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&");
}

/**
 * Pull `<source>`/`<translation>` pairs out of one `.ts` file.
 *
 * A regex rather than an XML parser, and that is a deliberate trade: the format is machine-generated by
 * `lupdate` with a fixed shape, this runs once to produce a checked-in artefact rather than at build
 * time, and the alternative is a dependency for a script nobody runs twice. A malformed pair is skipped
 * rather than guessed at.
 */
function harvest(path) {
  const xml = readFileSync(path, "utf8");
  const entries = new Map();
  let unfinished = 0;

  const messages = xml.matchAll(/<message[^>]*>([\s\S]*?)<\/message>/g);
  for (const [, body] of messages) {
    const src = body.match(/<source>([\s\S]*?)<\/source>/);
    const translated = body.match(/<translation([^>]*)>([\s\S]*?)<\/translation>/);
    if (!src || !translated) continue;

    // Qt marks an untranslated string `type="unfinished"`. Carrying those across would fill the
    // catalogue with English pretending to be translated.
    if (/type="unfinished"/.test(translated[1])) {
      unfinished += 1;
      continue;
    }

    const key = unescape(src[1]).trim();
    const value = unescape(translated[2]).trim();
    if (key && value && key !== value) entries.set(key, value);
  }

  return { entries, unfinished };
}

mkdirSync(out, { recursive: true });

const files = readdirSync(source).filter((f) => f.endsWith(".ts"));
const summary = [];

for (const file of files) {
  // `stacer_pt_BR.ts` -> `pt-BR`, `stacer_de.ts` -> `de`.
  const locale = basename(file, ".ts").replace(/^stacer_/, "").replace(/_/g, "-");
  const { entries, unfinished } = harvest(join(source, file));

  const sorted = Object.fromEntries([...entries.entries()].sort(([a], [b]) => a.localeCompare(b)));
  writeFileSync(join(out, `${locale}.json`), `${JSON.stringify(sorted, null, 2)}\n`);
  summary.push({ locale, translated: entries.size, unfinished });
}

summary.sort((a, b) => b.translated - a.translated);
console.log(`harvested ${summary.length} locales into src/locales/`);
for (const row of summary) {
  console.log(
    `  ${row.locale.padEnd(6)} ${String(row.translated).padStart(4)} translated` +
      (row.unfinished ? `, ${row.unfinished} left unfinished by Stacer and skipped` : ""),
  );
}
