// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing is holding the space.
 *
 * `Unknown` is a first-class category, not a bug: space nix cannot attribute is shown as
 * unattributed rather than silently dropped, which is what makes invariant 2 meaningful.
 */
export type Category = "package_payload" | "package_cache" | "app_cache" | "log" | "journal" | "trash" | "snapshot" | "container_image" | "build_artifact" | "thumbnail" | "crash_dump" | "orphaned_config" | "user_file" | "duplicate" | "unknown";
