// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one entry, stably across rescans.
 *
 * Derived from the entry's identity — its path, or its label for a logical entry — rather than
 * from insertion order, so a refresh does not invalidate the user's selection. That is invariant 5.
 */
export type EntryId = string;
