// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How nix concluded what an entry is. Shown in the UI, so a user can judge our reasoning.
 */
export type Provenance = { "by": "walked" } | { "by": "known_path", rule: string, } | { "by": "package_manager", backend: string, } | { "by": "project_marker", marker: string, } | { "by": "filesystem_tool", tool: string, };
