// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How space is actually reclaimed. Always prefers the owning tool over `unlink`.
 */
export type ReclaimMethod = { "method": "package_manager", command: string, } | { "method": "journal_vacuum", limit: string, } | { "method": "snap_revision", package: string, revision: string, } | { "method": "container_prune", scope: string, } | { "method": "trash_empty", volume: string, } | { "method": "move_to_trash", path: string, } | { "method": "unlink", path: string, };
