// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryId } from "./EntryId";
import type { SpaceEntry } from "./SpaceEntry";

/**
 * An arena of entries plus the roots, so the tree can be sent over IPC without cycles.
 */
export type SpaceTree = { 
/**
 * Every entry, keyed by id.
 *
 * `#[ts(as = ...)]` rather than `#[ts(type = ...)]`: a raw type *string* is emitted verbatim
 * with no import, which silently broke the generated module and collapsed every downstream
 * type to `any`. Naming a real Rust type instead lets ts-rs collect `SpaceEntry` as a
 * dependency and import it.
 */
entries: { [key in string]?: SpaceEntry }, 
/**
 * Top-level entries, in insertion order.
 */
roots: Array<EntryId>, };
