// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { EntryId } from "./EntryId";
import type { Provenance } from "./Provenance";
import type { ReclaimMethod } from "./ReclaimMethod";
import type { Safety } from "./Safety";

/**
 * One node: bytes attributed to a thing.
 */
export type SpaceEntry = { id: EntryId, 
/**
 * Absent for a logical entry that is not a path.
 */
path: string | null, 
/**
 * Human name: "Firefox cache", "linux-image-6.5.0-21".
 */
label: string, 
/**
 * Sum of file sizes.
 */
apparent_size: number, 
/**
 * On-disk blocks. Differs from apparent on sparse, compressed and copy-on-write filesystems,
 * which is why both are carried rather than one being called "the" size.
 */
allocated: number, category: Category, provenance: Provenance, safety: Safety, reclaim: ReclaimMethod | null, 
/**
 * Seconds since the Unix epoch, when known.
 */
last_used: number | null, 
/**
 * True for a directory, so the UI can offer to drill in.
 */
is_dir: boolean, 
/**
 * Immediate children. The model is a tree.
 */
children: Array<EntryId>, };
